// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjoinazbrnkhuhmcyhml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtqb2luYXpicm5raHVobWN5aG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MjcyMjYsImV4cCI6MjA3NDAwMzIyNn0.SwzCKC5LSIsojJMtISlGU3jMVQdTqdthRV0mWgN2O5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});